[squash] livepatch/klp-convert: cleanup whitespace, string breaks
Note: squash with ("livepatch: Add klp-convert tool")

Fixes checkpatch complaints:
  ERROR: code indent should use tabs where possible
  WARNING: please, no spaces at the start of a line
  WARNING: Avoid line continuations in quoted strings
  ERROR: spaces required around that '==' (ctx:VxV)

[joe:checkpatch nits]

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>