[squash] klp-convert: relax duplicate user symbol check
Note: squash with ("livepatch/selftests: add klp-convert")

Relax the duplicate user symbol position sanity check to allow for
duplicate symbol <object, name> combinations which specify the same
symbol <position> value.  This allows klp-convert to translate a
livepatch comprised of multiple object files that supply their own
KLP_MODULE_RELOC / SYMPOS data.

Fixes build error:

  klp-convert: Conflicting KLP_SYMPOS definition: vmlinux.state_show,1 vs. vmlinux.state_show,1.
  klp-convert: Unable to load user-provided sympos
  make[1]: *** [scripts/Makefile.modpost:148: lib/livepatch/test_klp_convert_multi_objs.ko] Error 255

Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>